/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedApprovazioniRouteImport } from './routes/_authenticated/approvazioni'
import { Route as AuthenticatedAttivitaRouteImport } from './routes/_authenticated/attivita'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDispositiviRouteImport } from './routes/_authenticated/dispositivi'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedLavorazioniRouteImport } from './routes/_authenticated/lavorazioni'
import { Route as AuthenticatedModuliRouteImport } from './routes/_authenticated/moduli'
import { Route as AuthenticatedNotificheRouteImport } from './routes/_authenticated/notifiche'
import { Route as AuthenticatedProfiloRouteImport } from './routes/_authenticated/profilo'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated/supervisor'
import { Route as AuthenticatedDispositiviCodeRouteImport } from './routes/_authenticated/dispositivi.$code'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as AuthenticatedModuliIndexRouteImport } from './routes/_authenticated/moduli.index'
import { Route as AuthenticatedModuliEnispaceRouteImport } from './routes/_authenticated/moduli.enispace'
import { Route as AuthenticatedModuliTrasportoMoneteRouteImport } from './routes/_authenticated/moduli.trasporto-monete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovazioniRoute =
  AuthenticatedApprovazioniRouteImport.update({
    id: '/approvazioni',
    path: '/approvazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttivitaRoute = AuthenticatedAttivitaRouteImport.update({
  id: '/attivita',
  path: '/attivita',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispositiviRoute =
  AuthenticatedDispositiviRouteImport.update({
    id: '/dispositivi',
    path: '/dispositivi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLavorazioniRoute =
  AuthenticatedLavorazioniRouteImport.update({
    id: '/lavorazioni',
    path: '/lavorazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModuliRoute = AuthenticatedModuliRouteImport.update({
  id: '/moduli',
  path: '/moduli',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificheRoute = AuthenticatedNotificheRouteImport.update({
  id: '/notifiche',
  path: '/notifiche',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfiloRoute = AuthenticatedProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispositiviCodeRoute =
  AuthenticatedDispositiviCodeRouteImport.update({
    id: '/$code',
    path: '/$code',
    getParentRoute: () => AuthenticatedDispositiviRoute,
  } as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModuliIndexRoute =
  AuthenticatedModuliIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedModuliRoute,
  } as any)
const AuthenticatedModuliEnispaceRoute =
  AuthenticatedModuliEnispaceRouteImport.update({
    id: '/enispace',
    path: '/enispace',
    getParentRoute: () => AuthenticatedModuliRoute,
  } as any)
const AuthenticatedModuliTrasportoMoneteRoute =
  AuthenticatedModuliTrasportoMoneteRouteImport.update({
    id: '/trasporto-monete',
    path: '/trasporto-monete',
    getParentRoute: () => AuthenticatedModuliRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/approvazioni': typeof AuthenticatedApprovazioniRoute
  '/attivita': typeof AuthenticatedAttivitaRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispositivi': typeof AuthenticatedDispositiviRouteWithChildren
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/lavorazioni': typeof AuthenticatedLavorazioniRoute
  '/moduli': typeof AuthenticatedModuliRouteWithChildren
  '/notifiche': typeof AuthenticatedNotificheRoute
  '/profilo': typeof AuthenticatedProfiloRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/dispositivi/$code': typeof AuthenticatedDispositiviCodeRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/moduli/enispace': typeof AuthenticatedModuliEnispaceRoute
  '/moduli/trasporto-monete': typeof AuthenticatedModuliTrasportoMoneteRoute
  '/moduli/': typeof AuthenticatedModuliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/approvazioni': typeof AuthenticatedApprovazioniRoute
  '/attivita': typeof AuthenticatedAttivitaRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispositivi': typeof AuthenticatedDispositiviRouteWithChildren
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/lavorazioni': typeof AuthenticatedLavorazioniRoute
  '/notifiche': typeof AuthenticatedNotificheRoute
  '/profilo': typeof AuthenticatedProfiloRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/dispositivi/$code': typeof AuthenticatedDispositiviCodeRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/moduli/enispace': typeof AuthenticatedModuliEnispaceRoute
  '/moduli/trasporto-monete': typeof AuthenticatedModuliTrasportoMoneteRoute
  '/moduli': typeof AuthenticatedModuliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/approvazioni': typeof AuthenticatedApprovazioniRoute
  '/_authenticated/attivita': typeof AuthenticatedAttivitaRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispositivi': typeof AuthenticatedDispositiviRouteWithChildren
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/lavorazioni': typeof AuthenticatedLavorazioniRoute
  '/_authenticated/moduli': typeof AuthenticatedModuliRouteWithChildren
  '/_authenticated/notifiche': typeof AuthenticatedNotificheRoute
  '/_authenticated/profilo': typeof AuthenticatedProfiloRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRoute
  '/_authenticated/dispositivi/$code': typeof AuthenticatedDispositiviCodeRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/_authenticated/moduli/enispace': typeof AuthenticatedModuliEnispaceRoute
  '/_authenticated/moduli/trasporto-monete': typeof AuthenticatedModuliTrasportoMoneteRoute
  '/_authenticated/moduli/': typeof AuthenticatedModuliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/approvazioni'
    | '/attivita'
    | '/audit'
    | '/chat'
    | '/dashboard'
    | '/dispositivi'
    | '/impostazioni'
    | '/lavorazioni'
    | '/moduli'
    | '/notifiche'
    | '/profilo'
    | '/setup'
    | '/supervisor'
    | '/dispositivi/$code'
    | '/jobs/$id'
    | '/moduli/enispace'
    | '/moduli/trasporto-monete'
    | '/moduli/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/approvazioni'
    | '/attivita'
    | '/audit'
    | '/chat'
    | '/dashboard'
    | '/dispositivi'
    | '/impostazioni'
    | '/lavorazioni'
    | '/notifiche'
    | '/profilo'
    | '/setup'
    | '/supervisor'
    | '/dispositivi/$code'
    | '/jobs/$id'
    | '/moduli/enispace'
    | '/moduli/trasporto-monete'
    | '/moduli'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/approvazioni'
    | '/_authenticated/attivita'
    | '/_authenticated/audit'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispositivi'
    | '/_authenticated/impostazioni'
    | '/_authenticated/lavorazioni'
    | '/_authenticated/moduli'
    | '/_authenticated/notifiche'
    | '/_authenticated/profilo'
    | '/_authenticated/setup'
    | '/_authenticated/supervisor'
    | '/_authenticated/dispositivi/$code'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/moduli/enispace'
    | '/_authenticated/moduli/trasporto-monete'
    | '/_authenticated/moduli/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvazioni': {
      id: '/_authenticated/approvazioni'
      path: '/approvazioni'
      fullPath: '/approvazioni'
      preLoaderRoute: typeof AuthenticatedApprovazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attivita': {
      id: '/_authenticated/attivita'
      path: '/attivita'
      fullPath: '/attivita'
      preLoaderRoute: typeof AuthenticatedAttivitaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispositivi': {
      id: '/_authenticated/dispositivi'
      path: '/dispositivi'
      fullPath: '/dispositivi'
      preLoaderRoute: typeof AuthenticatedDispositiviRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lavorazioni': {
      id: '/_authenticated/lavorazioni'
      path: '/lavorazioni'
      fullPath: '/lavorazioni'
      preLoaderRoute: typeof AuthenticatedLavorazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moduli': {
      id: '/_authenticated/moduli'
      path: '/moduli'
      fullPath: '/moduli'
      preLoaderRoute: typeof AuthenticatedModuliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifiche': {
      id: '/_authenticated/notifiche'
      path: '/notifiche'
      fullPath: '/notifiche'
      preLoaderRoute: typeof AuthenticatedNotificheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profilo': {
      id: '/_authenticated/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof AuthenticatedProfiloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispositivi/$code': {
      id: '/_authenticated/dispositivi/$code'
      path: '/$code'
      fullPath: '/dispositivi/$code'
      preLoaderRoute: typeof AuthenticatedDispositiviCodeRouteImport
      parentRoute: typeof AuthenticatedDispositiviRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moduli/': {
      id: '/_authenticated/moduli/'
      path: '/'
      fullPath: '/moduli/'
      preLoaderRoute: typeof AuthenticatedModuliIndexRouteImport
      parentRoute: typeof AuthenticatedModuliRoute
    }
    '/_authenticated/moduli/enispace': {
      id: '/_authenticated/moduli/enispace'
      path: '/enispace'
      fullPath: '/moduli/enispace'
      preLoaderRoute: typeof AuthenticatedModuliEnispaceRouteImport
      parentRoute: typeof AuthenticatedModuliRoute
    }
    '/_authenticated/moduli/trasporto-monete': {
      id: '/_authenticated/moduli/trasporto-monete'
      path: '/trasporto-monete'
      fullPath: '/moduli/trasporto-monete'
      preLoaderRoute: typeof AuthenticatedModuliTrasportoMoneteRouteImport
      parentRoute: typeof AuthenticatedModuliRoute
    }
  }
}

interface AuthenticatedDispositiviRouteChildren {
  AuthenticatedDispositiviCodeRoute: typeof AuthenticatedDispositiviCodeRoute
}

const AuthenticatedDispositiviRouteChildren: AuthenticatedDispositiviRouteChildren =
  {
    AuthenticatedDispositiviCodeRoute: AuthenticatedDispositiviCodeRoute,
  }

const AuthenticatedDispositiviRouteWithChildren =
  AuthenticatedDispositiviRoute._addFileChildren(
    AuthenticatedDispositiviRouteChildren,
  )

interface AuthenticatedModuliRouteChildren {
  AuthenticatedModuliEnispaceRoute: typeof AuthenticatedModuliEnispaceRoute
  AuthenticatedModuliTrasportoMoneteRoute: typeof AuthenticatedModuliTrasportoMoneteRoute
  AuthenticatedModuliIndexRoute: typeof AuthenticatedModuliIndexRoute
}

const AuthenticatedModuliRouteChildren: AuthenticatedModuliRouteChildren = {
  AuthenticatedModuliEnispaceRoute: AuthenticatedModuliEnispaceRoute,
  AuthenticatedModuliTrasportoMoneteRoute:
    AuthenticatedModuliTrasportoMoneteRoute,
  AuthenticatedModuliIndexRoute: AuthenticatedModuliIndexRoute,
}

const AuthenticatedModuliRouteWithChildren =
  AuthenticatedModuliRoute._addFileChildren(AuthenticatedModuliRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovazioniRoute: typeof AuthenticatedApprovazioniRoute
  AuthenticatedAttivitaRoute: typeof AuthenticatedAttivitaRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispositiviRoute: typeof AuthenticatedDispositiviRouteWithChildren
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedLavorazioniRoute: typeof AuthenticatedLavorazioniRoute
  AuthenticatedModuliRoute: typeof AuthenticatedModuliRouteWithChildren
  AuthenticatedNotificheRoute: typeof AuthenticatedNotificheRoute
  AuthenticatedProfiloRoute: typeof AuthenticatedProfiloRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRoute
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovazioniRoute: AuthenticatedApprovazioniRoute,
  AuthenticatedAttivitaRoute: AuthenticatedAttivitaRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispositiviRoute: AuthenticatedDispositiviRouteWithChildren,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedLavorazioniRoute: AuthenticatedLavorazioniRoute,
  AuthenticatedModuliRoute: AuthenticatedModuliRouteWithChildren,
  AuthenticatedNotificheRoute: AuthenticatedNotificheRoute,
  AuthenticatedProfiloRoute: AuthenticatedProfiloRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRoute,
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
