/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedApprovazioniRouteImport } from './routes/_authenticated/approvazioni'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLavorazioniRouteImport } from './routes/_authenticated/lavorazioni'
import { Route as AuthenticatedModuliRouteImport } from './routes/_authenticated/moduli'
import { Route as AuthenticatedNotificheRouteImport } from './routes/_authenticated/notifiche'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated/supervisor'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as AuthenticatedModuliIndexRouteImport } from './routes/_authenticated/moduli.index'
import { Route as AuthenticatedModuliEnispaceRouteImport } from './routes/_authenticated/moduli.enispace'
import { Route as AuthenticatedModuliTrasportoMoneteRouteImport } from './routes/_authenticated/moduli.trasporto-monete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovazioniRoute =
  AuthenticatedApprovazioniRouteImport.update({
    id: '/approvazioni',
    path: '/approvazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLavorazioniRoute =
  AuthenticatedLavorazioniRouteImport.update({
    id: '/lavorazioni',
    path: '/lavorazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModuliRoute = AuthenticatedModuliRouteImport.update({
  id: '/moduli',
  path: '/moduli',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificheRoute = AuthenticatedNotificheRouteImport.update({
  id: '/notifiche',
  path: '/notifiche',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModuliIndexRoute =
  AuthenticatedModuliIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedModuliRoute,
  } as any)
const AuthenticatedModuliEnispaceRoute =
  AuthenticatedModuliEnispaceRouteImport.update({
    id: '/enispace',
    path: '/enispace',
    getParentRoute: () => AuthenticatedModuliRoute,
  } as any)
const AuthenticatedModuliTrasportoMoneteRoute =
  AuthenticatedModuliTrasportoMoneteRouteImport.update({
    id: '/trasporto-monete',
    path: '/trasporto-monete',
    getParentRoute: () => AuthenticatedModuliRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/approvazioni': typeof AuthenticatedApprovazioniRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lavorazioni': typeof AuthenticatedLavorazioniRoute
  '/moduli': typeof AuthenticatedModuliRouteWithChildren
  '/notifiche': typeof AuthenticatedNotificheRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/moduli/enispace': typeof AuthenticatedModuliEnispaceRoute
  '/moduli/trasporto-monete': typeof AuthenticatedModuliTrasportoMoneteRoute
  '/moduli/': typeof AuthenticatedModuliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/approvazioni': typeof AuthenticatedApprovazioniRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lavorazioni': typeof AuthenticatedLavorazioniRoute
  '/notifiche': typeof AuthenticatedNotificheRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/moduli/enispace': typeof AuthenticatedModuliEnispaceRoute
  '/moduli/trasporto-monete': typeof AuthenticatedModuliTrasportoMoneteRoute
  '/moduli': typeof AuthenticatedModuliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/approvazioni': typeof AuthenticatedApprovazioniRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lavorazioni': typeof AuthenticatedLavorazioniRoute
  '/_authenticated/moduli': typeof AuthenticatedModuliRouteWithChildren
  '/_authenticated/notifiche': typeof AuthenticatedNotificheRoute
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/_authenticated/moduli/enispace': typeof AuthenticatedModuliEnispaceRoute
  '/_authenticated/moduli/trasporto-monete': typeof AuthenticatedModuliTrasportoMoneteRoute
  '/_authenticated/moduli/': typeof AuthenticatedModuliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/approvazioni'
    | '/dashboard'
    | '/lavorazioni'
    | '/moduli'
    | '/notifiche'
    | '/supervisor'
    | '/jobs/$id'
    | '/moduli/enispace'
    | '/moduli/trasporto-monete'
    | '/moduli/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/approvazioni'
    | '/dashboard'
    | '/lavorazioni'
    | '/notifiche'
    | '/supervisor'
    | '/jobs/$id'
    | '/moduli/enispace'
    | '/moduli/trasporto-monete'
    | '/moduli'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/approvazioni'
    | '/_authenticated/dashboard'
    | '/_authenticated/lavorazioni'
    | '/_authenticated/moduli'
    | '/_authenticated/notifiche'
    | '/_authenticated/supervisor'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/moduli/enispace'
    | '/_authenticated/moduli/trasporto-monete'
    | '/_authenticated/moduli/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvazioni': {
      id: '/_authenticated/approvazioni'
      path: '/approvazioni'
      fullPath: '/approvazioni'
      preLoaderRoute: typeof AuthenticatedApprovazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lavorazioni': {
      id: '/_authenticated/lavorazioni'
      path: '/lavorazioni'
      fullPath: '/lavorazioni'
      preLoaderRoute: typeof AuthenticatedLavorazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moduli': {
      id: '/_authenticated/moduli'
      path: '/moduli'
      fullPath: '/moduli'
      preLoaderRoute: typeof AuthenticatedModuliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifiche': {
      id: '/_authenticated/notifiche'
      path: '/notifiche'
      fullPath: '/notifiche'
      preLoaderRoute: typeof AuthenticatedNotificheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moduli/': {
      id: '/_authenticated/moduli/'
      path: '/'
      fullPath: '/moduli/'
      preLoaderRoute: typeof AuthenticatedModuliIndexRouteImport
      parentRoute: typeof AuthenticatedModuliRoute
    }
    '/_authenticated/moduli/enispace': {
      id: '/_authenticated/moduli/enispace'
      path: '/enispace'
      fullPath: '/moduli/enispace'
      preLoaderRoute: typeof AuthenticatedModuliEnispaceRouteImport
      parentRoute: typeof AuthenticatedModuliRoute
    }
    '/_authenticated/moduli/trasporto-monete': {
      id: '/_authenticated/moduli/trasporto-monete'
      path: '/trasporto-monete'
      fullPath: '/moduli/trasporto-monete'
      preLoaderRoute: typeof AuthenticatedModuliTrasportoMoneteRouteImport
      parentRoute: typeof AuthenticatedModuliRoute
    }
  }
}

interface AuthenticatedModuliRouteChildren {
  AuthenticatedModuliEnispaceRoute: typeof AuthenticatedModuliEnispaceRoute
  AuthenticatedModuliTrasportoMoneteRoute: typeof AuthenticatedModuliTrasportoMoneteRoute
  AuthenticatedModuliIndexRoute: typeof AuthenticatedModuliIndexRoute
}

const AuthenticatedModuliRouteChildren: AuthenticatedModuliRouteChildren = {
  AuthenticatedModuliEnispaceRoute: AuthenticatedModuliEnispaceRoute,
  AuthenticatedModuliTrasportoMoneteRoute:
    AuthenticatedModuliTrasportoMoneteRoute,
  AuthenticatedModuliIndexRoute: AuthenticatedModuliIndexRoute,
}

const AuthenticatedModuliRouteWithChildren =
  AuthenticatedModuliRoute._addFileChildren(AuthenticatedModuliRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovazioniRoute: typeof AuthenticatedApprovazioniRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLavorazioniRoute: typeof AuthenticatedLavorazioniRoute
  AuthenticatedModuliRoute: typeof AuthenticatedModuliRouteWithChildren
  AuthenticatedNotificheRoute: typeof AuthenticatedNotificheRoute
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRoute
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovazioniRoute: AuthenticatedApprovazioniRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLavorazioniRoute: AuthenticatedLavorazioniRoute,
  AuthenticatedModuliRoute: AuthenticatedModuliRouteWithChildren,
  AuthenticatedNotificheRoute: AuthenticatedNotificheRoute,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRoute,
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
